### ISSUE TITLE
TypeError: PostOrPut() got multiple values for keyword argument 'extra_headers'

### ISSUE THREAD

**Issue by mbrenig** [mbrenig/SheetSync#6]
ERROR:gdata:gdata API error. PostOrPut() got multiple values for keyword argument 'extra_headers'
Traceback (most recent call last):
  File "T:\Migration\GoldenMasterTools\sip_validator.py", line 104, in <module>
    source.sync(sip_data)
  File "C:\Python27\lib\site-packages\sheetsync\__init__.py", line 864, in sync
    return self._update(raw_data, row_change_callback, delete_rows=True)
  File "C:\Python27\lib\site-packages\sheetsync\__init__.py", line 918, in _update
    row_change_callback):
  File "C:\Python27\lib\site-packages\sheetsync\__init__.py", line 1063, in _change_row
    self._write_cell(cell_elem)
  File "C:\Python27\lib\site-packages\sheetsync\__init__.py", line 620, in _write_cell
    self._flush_writes()
  File "C:\Python27\lib\site-packages\sheetsync\__init__.py", line 633, in _flush_writes
    raise e
TypeError: PostOrPut() got multiple values for keyword argument 'extra_headers'

**Comment by mbrenig** [comment]
Hi Ash, I've just published a newer version (0.1.5)  https://pypi.python.org/pypi/sheetsync/0.1.5  which should fix most occurrences of this problem. You can upgrade to it with "pip install -U sheetsync".
Let me know how it goes.
M
